AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  The SAM template for sending AWS billing report to your Slack channel.

Parameters:
  SlackIncomingWebhookUrl:
    Description: URL to which you send a JSON payload to Slack
    Type: String
  SlackChannel:
    Description: The name of Slack channel
    Type: String
    Default: '#general'
  TargetCurrency:
    Description: the target currency ISO code
    Type: String
    Default: USD

Resources:
  AwsBillingReporterLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.6
      CodeUri: package.zip
      FunctionName: aws-billing-report-to-slack-handler
      Description: |
        Lambda function that sends AWS billing report to your Slack channel.
      MemorySize: 128
      Timeout: 20
      Policies:
        # managed policies
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        # inline policies
        - Statement:
          - Effect: Allow
            Action:
            - ce:GetCostAndUsage
            Resource: '*'
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackIncomingWebhookUrl
          SLACK_CHANNEL: !Ref SlackChannel
          TARGET_CURRENCY: !Ref TargetCurrency
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)

  AwsBillingReporterLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${LambdaFunctionName}
        - LambdaFunctionName: !Ref AwsBillingReporterLambdaFunction
      RetentionInDays: 30
    DeletionPolicy: Delete
